name: RoseAntiF5
author: EmSockz
main: me.emsockz.antif5.Main
api-version: 1.13
version: 0.1
commands:
  antif5:
    usage: /<command>
    aliases: [roseantif5, f5]
permissions:
  roseantif5.*:
    description: All perms
    default: op
    children:
      roseantif5.commands.*: true
      roseantif5.commands.help: true
      roseantif5.commands.reload: true
  roseantif5.commands.help:
    description: Show command help
  roseantif5.commands.reload:
    description: Reload plugin