lang: "en"
enableAntiF5: true
blacklistPlayers:
 - "EmSockz"
antiF5Item:
  stand:
    Material: WOODEN_SHOVEL
    CustomModelData: 1000
  sneak:
    Material: WOODEN_SHOVEL
    CustomModelData: 1001
  swim:
    Material: WOODEN_SHOVEL
    CustomModelData: 1002
  crawl:
    Material: WOODEN_SHOVEL
    CustomModelData: 1003

